// AUTO-GENERATED by scripts/sync-feature-flags-defaults.js
// 真相来源: cloudfunctions/shared/feature-flags-defaults.json
// 切勿手动修改；改请改源文件后跑 `npm run sync:feature-flags-defaults`。
module.exports = {
  "show_station_entry": false,
  "show_pickup_entry": true,
  "enable_logistics_entry": true,
  "enable_lottery_entry": true,
  "enable_activity_entry": true
};
